name: deploy-on-pages
on: workflow_dispatch
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
  get-tag:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Get Current tag"
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0 --match 'v*[0-9]')" >> $GITHUB_ENV
      - name: Get issue
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          ISSUE_TITLE="RELEASE ${{ env.tag }}"
          ISSUE_ID=$(gh issue list --json number,title,labels -q \
            ".[] | select(.title == \"${ISSUE_TITLE}\" and .labels[].name == \"RELEASE\") | .number")
          if [ ! -z "$ISSUE_ID" ]; then
            gh issue close $ISSUE_ID -c "Deployed to [https://anakharsis9.github.io/ci-hw/](https://anakharsis9.github.io/ci-hw/)" -r "completed"
          fi
