name: Create release
permissions:
  contents: read
  issues: write
on:
  push:
    tags:
      - v\d+
jobs:
  run-autotests:
    uses: ./.github/workflows/testing.yml
  create-issue:
    if: success() || failure()
    needs: run-autotests
    runs-on: ubuntu-latest
    steps:
      - name: Get creation date
        run: echo "CREATION_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Get Previous tag"
        id: previoustag
        run: echo "tag=$(git describe --tags --abbrev=0 --match 'v*[0-9]' HEAD~)" >> $GITHUB_OUTPUT
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.ref_name }}
          base-ref: ${{ steps.previoustag.outputs.tag }}
      - name: Create an issue
        id: create-issue
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.ref_name }}
          author: ${{ github.actor }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          creation_date: ${{ env.CREATION_DATE }}
          unit_result: ${{ needs.run-autotests.outputs.unit_result }}
          unit_link: ${{ needs.run-autotests.outputs.unit_link }}
          e2e_result: ${{ needs.run-autotests.outputs.e2e_result }}
          lint_result: ${{ needs.run-autotests.outputs.lint_result }}
        with:
          update_existing: true
          search_existing: all
      - run: "echo Created ${{ steps.create-issue.outputs.url }}"
  
