name: Create release
permissions:
  contents: read
  issues: write
on:
  push:
    tags:
      - v\d+
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get creation date
        run: echo "CREATION_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Get Previous tag"
        id: previoustag
        uses: jimschubert/query-tag-action@v1
        with:
          include: v\d+
          commit-ish: 'HEAD~'
          skip-unshallow: 'true'
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.ref_name }}
          base-ref: ${{ steps.previoustag.outputs.tag }}
      - name: Create an issue
        id: create-issue
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.ref_name }}
          author: ${{ github.actor }}
          changelog: ${{ steps.changelog.outputs.changelog }}
        with:
          update_existing: true
          search_existing: all
      - run: "echo Created ${{ steps.create-issue.outputs.url }}"
  run-autotests:
    uses: ./.github/workflows/testing.yml
  # update-issue:
  #   needs: [create-issue, run-autotests]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Update an issue
  #       id: update-issue
  #       uses: JasonEtco/create-an-issue@v2.9.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         version: ${{ github.ref_name }}
  #         author: ${{ github.actor }}
  #       with:
  #           update_existing: true
  #           search_existing: all
