name: check autotests
on:
  workflow_call:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Set exit code to unit_result
        run: |
          if [ "$?" != "0" ]; then
            echo "lint_result='Test failed'" >> $GITHUB_ENV
          else
            echo "lint_result='Test passed'" >> $GITHUB_ENV
          fi
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run e2e tests
        run: npm run e2e
      - name: Set exit code to e2e_result
        run: |
          if [ "$?" != "0" ]; then
            echo "lint_result='Test failed'" >> $GITHUB_ENV
          else
            echo "lint_result='Test passed'" >> $GITHUB_ENV
          fi
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run eslint
        run: npm run lint
      - name: Set exit code to lint_result
        run: |
          if [ "$?" != "0" ]; then
            echo "lint_result='Test failed'" >> $GITHUB_ENV
          else
            echo "lint_result='Test passed'" >> $GITHUB_ENV
          fi
