name: check autotests
on:
  workflow_call:
    outputs:
      unit_result:
        value: ${{ jobs.run-unit-tests.outputs.unit_result }}
      e2e_result:
        value: ${{ jobs.run-e2e-tests.outputs.e2e_result }}
      lint_result:
        value: ${{ jobs.run-eslint.outputs.lint_result }}
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Set exit code to unit_result
        if: success() || failure()
        id: unit
        run: |
          if [ "$?" != "0" ]; then
            echo "unit_result=Test failed" >> $GITHUB_OUTPUT
          else
            echo "unit_result=Test passed" >> $GITHUB_OUTPUT
          fi
    outputs: 
      unit_result: ${{ steps.unit.outputs.unit_result }}
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run e2e tests
        run: npm run e2e
      - name: Set exit code to e2e_result
        if: success() || failure()
        id: e2e
        run: |
          if [ "$?" != "0" ]; then
            echo "e2e_result=Test failed" >> $GITHUB_OUTPUT
          else
            echo "e2e_result=Test passed" >> $GITHUB_OUTPUT
          fi
    outputs: 
      e2e_result: ${{ steps.e2e.outputs.e2e_result }}
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run eslint
        run: npm run lint
      - name: Set exit code to lint_result
        if: success() || failure()
        id: lint
        run: |
          if [ "$?" != "0" ]; then
            echo "lint_result=Test failed" >> $GITHUB_OUTPUT
          else
            echo "lint_result=Test passed" >> $GITHUB_OUTPUT
          fi
    outputs:
      lint_result: ${{ steps.lint.outputs.lint_result }}
