name: check autotests
on: 
  pull_request:
    branches: [ master ]
    types: [ opened, edited ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Install playwright
        run: npx playwright install --with-deps chromium
      - name: Run e2e tests
        run: npm run e2e
      - name: Run eslint
        run: npm run lint
