name: check autotests
on:
  workflow_call:
    outputs:
      workflow_link:
        value: ${{ jobs.run-unit-tests.outputs.workflow_link }}
      unit_result:
        value: ${{ jobs.run-unit-tests.outputs.unit_result }}
      e2e_result:
        value: ${{ jobs.run-e2e-tests.outputs.e2e_result }}
      lint_result:
        value: ${{ jobs.run-eslint.outputs.lint_result }}
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run unit tests
        id: unit
        run: npm test
      - name: Set success
        if: success()
        run: echo "unit_result=Test passed" >> $GITHUB_ENV
      - name: Set fail
        if: failure()
        run: echo "unit_result=Test failed" >> $GITHUB_ENV
      - name: Set workflow_link
        if: success() || failure()
        id: workflow_link
        run: echo "workflow_link=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" >> $GITHUB_OUTPUT
    outputs:
      unit_result: ${{ env.unit_result }}
      workflow_link: ${{ steps.workflow_link.outputs.workflow_link }}
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run e2e tests
        id: e2e
        run: npm run e2e
      - name: Set success
        if: success()
        run: echo "e2e_result=Test passed" >> $GITHUB_ENV
      - name: Set fail
        if: failure()
        run: echo "e2e_result=Test failed" >> $GITHUB_ENV
    outputs:
      e2e_result: ${{ env.e2e_result }}
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run eslint
        id: lint
        run: npm run lint
      - name: Set success
        if: success()
        run: echo "lint_result=Test passed" >> $GITHUB_ENV
      - name: Set fail
        if: failure()
        run: echo "lint_result=Test failed" >> $GITHUB_ENV
    outputs:
      lint_result: ${{ env.lint_result }}
