name: test-react-app
on: 
  pull_request:
    branches: [ master ]
    types: [ opened, edited ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run unit tests
        run: npm test
